### ISSUE TITLE
Dose mono-assembly-injector still work?

### ISSUE THREAD

**Issue by Jeswang** [gamebooster/mono-assembly-injector#1]
I want to inject into hearthstone and do some script, I see your work here. And I tried similar way on Mac. I successfully get all the function pointers but they are all returning 0.

I wonder whether your work still working?

**Comment by skomski** [comment]
only tested on windows - no idea what exactly is different on mac

**Comment by Jeswang** [comment]
@Skomski Already solve it. It seems need to run 

```
mono_thread_attach(mono_get_root_domain());
```

before load DLL file.
