### ISSUE TITLE
Win10 Issue (tested with Build 10158)

### ISSUE THREAD

**Issue by sailro** [gamebooster/mono-assembly-injector#2]
The injector is working properly with my Win8.1 configuration.

But when using Win10 (tested with Build 10158), the injector fails with an access violation.
`First-chance exception at 0x545131CA (msvcr120d.dll) in injector.exe: 0xC0000005: Access violation reading location 0x3CBA0000.`

The problem is related to the blackbone library, in the OS dependent api set initialization.

First `IsWindows8Point1OrGreater()` method is not returning the expected value. But whatever the result is, even when forcing the value, `bool blackbone::NameResolve::InitializeP()` is failing at this line:
`std::wstring hostName( reinterpret_cast<wchar_t*>(reinterpret_cast<uint8_t*>(pSetMap)+pHost->ValueOffset), pHost->ValueLength / sizeof(wchar_t) );`

**Comment by skomski** [comment]
Since BlackBone has commits like https://github.com/DarthTon/Blackbone/commit/9a3441157b1ded2c89d42c5c714409099e8ae206 it should work when you update it

**Comment by sailro** [comment]
Thanks, this is working properly. I made a PR if you want to update to the latest BlackBone version.
